// Generated by LiveScript 1.2.0
(function(){
  var url;
  url = 'data.json';
  d3.json(url, function(org){
    var data, max, name, scale, x$;
    data = [];
    max = null;
    for (name in org) {
      data.push({
        n: name,
        v: org[name][0]
      });
      if (!(org[name][0] < max)) {
        max = org[name][0];
      }
    }
    scale = d3.scale.linear().domain([0, max]).range([0, 500]);
    data.sort(function(){
      return d3.descending(arguments[0].v, arguments[1].v);
    });
    x$ = d3.select('#visual').selectAll('svg').data(data).enter().append('svg').attr('class', 'c');
    x$.append('circle').attr('r', function(){
      return scale(arguments[0].v);
    }).attr('cy', function(){
      return 100;
    }).attr('cx', function(){
      return 100;
    }).style('stroke', '#00FFFF').style('fill', '#FF0000');
    return x$;
  });
}).call(this);
